from datetime import datetime, timezone
from pathlib import Path

import pytest

from credforge.enums import AuthScheme, CredentialType, PipelineStage, ReasonCode, StageStatus
from credforge.models.registry_entities import RegistryEntry
from credforge.pipeline.provision import provision
from credforge.providers.browser import ProvisionOutcome, ProvisionStepResult
from credforge.providers.email import EmailMessage
from credforge.redaction import scrub_secrets
from credforge.registry.store import AppendOnlyRegistry
from credforge.vault.crypto_vault import FernetVault, VaultRefNotFoundError, generate_key


class FakeEmailProvider:
    def __init__(self) -> None:
        self.alias_calls: list[str] = []

    def alias_for(self, identity_key: str) -> str:
        self.alias_calls.append(identity_key)
        return f"credforge+{identity_key}@example.com"

    async def wait_for_message(self, **kwargs) -> EmailMessage:
        raise NotImplementedError


class FakeBrowserDriver:
    def __init__(self, outcome: ProvisionOutcome) -> None:
        self._outcome = outcome
        self.calls = 0
        self.received_account_password: str | None = None

    async def signup_and_create_app(self, *, account_password: str, **kwargs) -> ProvisionOutcome:
        self.calls += 1
        self.received_account_password = account_password
        # Mimics a real driver: echoes back the password it actually
        # received and used, not a canned value disconnected from it.
        if self._outcome.account_password_used is not None:
            return self._outcome.model_copy(update={"account_password_used": account_password})
        return self._outcome


def _success_outcome(*, with_password: bool = True) -> ProvisionOutcome:
    return ProvisionOutcome(
        success=True,
        credential_type=CredentialType.OAUTH2_TOKEN_PAIR,
        raw_api_credential={"client_id": "abc", "client_secret": "xyz"},
        account_password_used="s3cr3t-generated-pw" if with_password else None,
        console_url="https://developer.example.com/apps/abc",
        steps=[ProvisionStepResult(step="signup", success=True)],
    )


def _failure_outcome() -> ProvisionOutcome:
    return ProvisionOutcome(
        success=False,
        credential_type=CredentialType.NONE,
        steps=[ProvisionStepResult(step="signup", success=False, detail="CAPTCHA blocked automation")],
        failure_reason="CAPTCHA blocked automation",
    )


def _vault(tmp_path: Path) -> FernetVault:
    return FernetVault(key=generate_key(), path=tmp_path / "vault.json")


def _registry(tmp_path: Path) -> AppendOnlyRegistry:
    return AppendOnlyRegistry(tmp_path / "registry.jsonl")


@pytest.mark.asyncio
async def test_successful_provision_stores_account_and_api_credentials_separately(tmp_path: Path) -> None:
    vault = _vault(tmp_path)
    registry = _registry(tmp_path)
    email = FakeEmailProvider()
    browser = FakeBrowserDriver(_success_outcome())

    result = await provision(
        "example.com",
        app_name="Example",
        developer_portal_url="https://developer.example.com",
        redirect_uris=["https://credforge.local/callback"],
        auth_scheme=AuthScheme.OAUTH2_AUTH_CODE,
        email=email,
        browser=browser,
        vault=vault,
        registry=registry,
        run_id="run_1",
        settings_fingerprint="fp1",
    )

    assert result.status == "provisioned"
    assert result.credential_type == CredentialType.OAUTH2_TOKEN_PAIR

    # Account-level: real password was generated by provision() itself (not
    # the driver) and handed to the driver, which echoed it back as used.
    assert result.account_email == "credforge+example.com@example.com"
    assert result.account_password_ref == "vault://example.com/account_password"
    assert vault.retrieve(result.account_password_ref) == {"password": browser.received_account_password}
    assert browser.received_account_password  # a real, non-empty generated password was passed in

    # API-level: client_id stays plaintext (not secret), client_secret is vaulted separately.
    assert result.client_id == "abc"
    assert result.client_secret_ref == "vault://example.com/client_secret"
    assert vault.retrieve(result.client_secret_ref) == {"client_secret": "xyz"}
    assert result.api_key_ref is None  # this outcome never produced an api_key

    entries = registry.load_all()
    assert len(entries) == 1
    assert entries[0].stage == PipelineStage.PROVISION
    assert entries[0].stage_status == StageStatus.COMPLETED
    assert entries[0].client_secret_ref == result.client_secret_ref
    assert entries[0].account_password_vault_ref == result.account_password_ref
    assert entries[0].client_id == "abc"
    assert entries[0].email_alias == "credforge+example.com@example.com"
    assert entries[0].closed is False


@pytest.mark.asyncio
async def test_generated_account_password_and_api_secrets_are_registered_for_redaction(tmp_path: Path) -> None:
    # Every real secret this stage mints (the generated account password,
    # and each API-level secret the signup flow returns) must be
    # registered with the redaction registry the moment it exists -- so
    # it can never appear in a log line or an --explain message, even one
    # written by code that has no idea this specific value is sensitive.
    # A realistic-length fake secret, deliberately -- a 3-character
    # client_secret ("xyz") would be shorter than register_secret()'s own
    # minimum-length guard (D-045) and never actually get registered,
    # making this test pass for the wrong reason.
    realistic_secret = "a-realistic-length-client-secret-value-123456"
    vault = _vault(tmp_path)
    registry = _registry(tmp_path)
    browser = FakeBrowserDriver(
        ProvisionOutcome(
            success=True,
            credential_type=CredentialType.OAUTH2_TOKEN_PAIR,
            raw_api_credential={"client_id": "abc", "client_secret": realistic_secret},
            account_password_used="placeholder",  # overwritten by FakeBrowserDriver's echo-back
            console_url="https://developer.redact-example.com/apps/abc",
            steps=[],
        )
    )

    result = await provision(
        "redact-example.com",
        app_name="RedactExample",
        developer_portal_url="https://developer.redact-example.com",
        redirect_uris=[],
        auth_scheme=AuthScheme.OAUTH2_AUTH_CODE,
        email=FakeEmailProvider(),
        browser=browser,
        vault=vault,
        registry=registry,
        run_id="run_1",
        settings_fingerprint="fp1",
    )

    assert browser.received_account_password  # sanity: a real password was actually generated
    message = f"debug: account_password={browser.received_account_password} client_secret={realistic_secret}"
    scrubbed = scrub_secrets(message)

    assert browser.received_account_password not in scrubbed
    assert realistic_secret not in scrubbed
    assert result.client_id == "abc"  # client_id is not secret -- deliberately never registered


@pytest.mark.asyncio
async def test_a_password_is_generated_fresh_every_call_not_reused(tmp_path: Path) -> None:
    vault = _vault(tmp_path)
    browser1 = FakeBrowserDriver(_success_outcome())
    browser2 = FakeBrowserDriver(_success_outcome())

    await provision(
        "a.example.com", app_name="A", developer_portal_url="https://developer.a.example.com", redirect_uris=[],
        auth_scheme=AuthScheme.OAUTH2_AUTH_CODE, email=FakeEmailProvider(), browser=browser1,
        vault=vault, registry=_registry(tmp_path), run_id="run_1", settings_fingerprint="fp1",
    )
    registry2 = AppendOnlyRegistry(tmp_path / "registry2.jsonl")
    await provision(
        "b.example.com", app_name="B", developer_portal_url="https://developer.b.example.com", redirect_uris=[],
        auth_scheme=AuthScheme.OAUTH2_AUTH_CODE, email=FakeEmailProvider(), browser=browser2,
        vault=vault, registry=registry2, run_id="run_1", settings_fingerprint="fp1",
    )

    assert browser1.received_account_password != browser2.received_account_password


@pytest.mark.asyncio
async def test_vendor_flow_with_no_password_field_leaves_account_password_ref_none(tmp_path: Path) -> None:
    # NASA's real flow: a form -> key delivered by email, no login, no
    # password at all. account_password_ref must be None, not a
    # placeholder for a password nothing ever used.
    vault = _vault(tmp_path)
    registry = _registry(tmp_path)
    browser = FakeBrowserDriver(_success_outcome(with_password=False))
    browser._outcome = ProvisionOutcome(
        success=True, credential_type=CredentialType.API_KEY,
        raw_api_credential={"api_key": "DEMO_KEY_12345"}, account_password_used=None,
        console_url="https://api.nasa.gov/", steps=[],
    )

    result = await provision(
        "api.nasa.gov", app_name="NASA API", developer_portal_url="https://api.nasa.gov/",
        redirect_uris=[], auth_scheme=AuthScheme.API_KEY, email=FakeEmailProvider(), browser=browser,
        vault=vault, registry=registry, run_id="run_1", settings_fingerprint="fp1",
    )

    assert result.status == "provisioned"
    assert result.account_password_ref is None
    assert result.api_key_ref == "vault://api.nasa.gov/api_key"
    assert vault.retrieve(result.api_key_ref) == {"api_key": "DEMO_KEY_12345"}


@pytest.mark.asyncio
async def test_none_auth_scheme_skips_signup_entirely(tmp_path: Path) -> None:
    # Open-Meteo's case: a genuinely open API. Provisioning "succeeds"
    # trivially -- no browser, no email, nothing to vault -- with an
    # explicit no-credential-required state, not a null that looks like
    # a failure.
    vault = _vault(tmp_path)
    registry = _registry(tmp_path)
    email = FakeEmailProvider()
    browser = FakeBrowserDriver(_success_outcome())

    result = await provision(
        "open-meteo.com", app_name="Open-Meteo", developer_portal_url="https://open-meteo.com/",
        redirect_uris=[], auth_scheme=AuthScheme.NONE, email=email, browser=browser,
        vault=vault, registry=registry, run_id="run_1", settings_fingerprint="fp1",
    )

    assert result.status == "provisioned"
    assert result.credential_type == CredentialType.NONE
    assert result.account_email is None
    assert result.account_password_ref is None
    assert result.api_key_ref is None
    assert email.alias_calls == []  # never touched
    assert browser.calls == 0  # never touched

    entries = registry.load_all()
    assert len(entries) == 1
    assert entries[0].credential_type == CredentialType.NONE


@pytest.mark.asyncio
async def test_idempotency_guard_short_circuits_before_any_provider_call(tmp_path: Path) -> None:
    # The guard that must hold even across a crash with no other bookkeeping:
    # provision() checks the registry for an existing open credential BEFORE
    # touching the browser/email provider at all.
    vault = _vault(tmp_path)
    registry = _registry(tmp_path)
    registry.append(
        RegistryEntry(
            identity_key="example.com",
            app_name="Example",
            run_id="run_0",
            stage=PipelineStage.PROVISION,
            stage_status=StageStatus.COMPLETED,
            settings_fingerprint="fp0",
            recorded_at=datetime.now(timezone.utc),
            email_alias="credforge+example.com@example.com",
            console_url="https://developer.example.com/apps/existing",
            credential_type=CredentialType.OAUTH2_TOKEN_PAIR,
            client_id="abc",
            client_secret_ref="vault://example.com/client_secret",
            account_password_vault_ref="vault://example.com/account_password",
            closed=False,
        )
    )
    email = FakeEmailProvider()
    browser = FakeBrowserDriver(_success_outcome())

    result = await provision(
        "example.com",
        app_name="Example",
        developer_portal_url="https://developer.example.com",
        redirect_uris=[],
        auth_scheme=AuthScheme.OAUTH2_AUTH_CODE,
        email=email,
        browser=browser,
        vault=vault,
        registry=registry,
        run_id="run_1",
        settings_fingerprint="fp1",
    )

    assert result.status == "already_provisioned"
    assert result.client_id == "abc"
    assert result.client_secret_ref == "vault://example.com/client_secret"
    assert result.account_password_ref == "vault://example.com/account_password"
    assert email.alias_calls == []
    assert browser.calls == 0


@pytest.mark.asyncio
async def test_failed_signup_never_writes_to_vault_or_registry(tmp_path: Path) -> None:
    # Failure drill: a single failed provisioning attempt must not leave a
    # partial vault entry or a registry entry pointing at a credential that
    # was never actually stored.
    vault = _vault(tmp_path)
    registry = _registry(tmp_path)
    email = FakeEmailProvider()
    browser = FakeBrowserDriver(_failure_outcome())

    result = await provision(
        "example.com",
        app_name="Example",
        developer_portal_url="https://developer.example.com",
        redirect_uris=[],
        auth_scheme=AuthScheme.OAUTH2_AUTH_CODE,
        email=email,
        browser=browser,
        vault=vault,
        registry=registry,
        run_id="run_1",
        settings_fingerprint="fp1",
    )

    assert result.status == "failed"
    assert result.reason_code == ReasonCode.PROVISION_FAILED
    assert registry.load_all() == []
    with pytest.raises(VaultRefNotFoundError):
        vault.retrieve("vault://example.com/client_secret")


@pytest.mark.asyncio
async def test_reprovisioning_after_a_closed_account_creates_a_new_entry(tmp_path: Path) -> None:
    # A previously closed (revoked) account must NOT short-circuit -- the
    # idempotency guard exists to avoid a duplicate *live* account, not to
    # refuse ever provisioning this vendor again.
    vault = _vault(tmp_path)
    registry = _registry(tmp_path)
    registry.append(
        RegistryEntry(
            identity_key="example.com",
            app_name="Example",
            run_id="run_0",
            stage=PipelineStage.PROVISION,
            stage_status=StageStatus.COMPLETED,
            settings_fingerprint="fp0",
            recorded_at=datetime.now(timezone.utc),
            client_secret_ref="vault://example.com/client_secret-old",
            closed=True,
        )
    )
    email = FakeEmailProvider()
    browser = FakeBrowserDriver(_success_outcome())

    result = await provision(
        "example.com",
        app_name="Example",
        developer_portal_url="https://developer.example.com",
        redirect_uris=[],
        auth_scheme=AuthScheme.OAUTH2_AUTH_CODE,
        email=email,
        browser=browser,
        vault=vault,
        registry=registry,
        run_id="run_1",
        settings_fingerprint="fp1",
    )

    assert result.status == "provisioned"
    assert browser.calls == 1
